name: Main Workflow

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Load Yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install
        env:
          CI: true

      - name: Build packages
        run: yarn build

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: "ci(changesets): version packages"
          title: "ci(changesets): version packages"
        env:
          NPM_TOKEN: ${{ secrets.JOY_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.JOY_GITHUB_TOKEN }}

      - name: Update changelog
        if: steps.changesets.outputs.published == 'true'
        run: |
          yarn changelog:write
          yarn changelog:commit

      - name: Release to @dev tag
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout main
          yarn changeset version --snapshot dev
          yarn changeset publish --tag dev
        env:
          NPM_TOKEN: ${{ secrets.JOY_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.JOY_GITHUB_TOKEN }}

      - name: Update changelog
        if: steps.changesets.outputs.published == 'true'
        run: |
          yarn changelog:gen
          yarn changelog:write
          yarn changelog:commit
